"""Deterministic categorization into the fixed taxonomy (core/taxonomy.py).

The fast, free, offline first tier shared by every ingest source:
- **Bank (Plaid):** map Plaid's Personal Finance Category (already merchant-derived) to our
  taxonomy — the strongest signal, so it's tried first.
- **Manual / fallback:** a comprehensive keyword + merchant classifier over the item name.
- **Receipts:** the vision model picks from the taxonomy in the prompt; this service is the
  fallback if it declines, and it backfills historical bank rows in the migration.

For manual entries, if this returns ``Other`` the caller may escalate to the Gemini
fallback (services/extract.classify_category) — the "hybrid" path. This module itself stays
**pure and deterministic** (no I/O), so it's fully unit-testable and stable across the app.

Matching is **token-bounded** (a keyword matches only when not glued to other letters or
digits), so short keywords like ``gas`` match "shell gas" but not "las vegas", and ``bar``
would match "wine bar" but not "barber".
"""

from __future__ import annotations

import re

from app.core.taxonomy import REGULAR_CATEGORIES

OTHER = "Other"
_VALID = set(REGULAR_CATEGORIES)

# Plaid personal_finance_category PRIMARY → our category. Income/transfers/loan-payments are
# filtered out upstream as non-spending, so they aren't mapped here.
PLAID_PFC_MAP: dict[str, str] = {
    "FOOD_AND_DRINK": "Food and Drinks",
    "GENERAL_MERCHANDISE": "Shopping",
    "HOME_IMPROVEMENT": "Shopping",
    "PERSONAL_CARE": "Shopping",
    "ENTERTAINMENT": "Entertainment",
    "TRANSPORTATION": "Travel/Transportation",
    "TRAVEL": "Travel/Transportation",
    "MEDICAL": "Health",
    "GENERAL_SERVICES": "Services",
    "RENT_AND_UTILITIES": "Services",
    "BANK_FEES": "Services",
    "GOVERNMENT_AND_NON_PROFIT": "Other",
}

# Keyword / merchant substrings → category. First category with a hit wins, IN THIS ORDER,
# so specific buckets are checked before broad ones and known collisions resolve correctly:
#   - Food is before Travel/Transportation so "uber eats" (food) beats "uber" (rides).
#   - Shopping is LAST because "store"/"shop" are broad (a "coffee shop" is Food first).
# All lowercase; matched as bounded tokens (see _compile). Keep merchant names specific
# enough to avoid false hits; the confirm screen stays editable as the safety net.
_KEYWORDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "Health",
        (
            "pharmacy",
            "pharmacies",
            "drugstore",
            "cvs",
            "walgreens",
            "rite aid",
            "duane reade",
            "doctor",
            "physician",
            "clinic",
            "medical",
            "med center",
            "hospital",
            "urgent care",
            "emergency room",
            "dental",
            "dentist",
            "orthodontist",
            "orthodontics",
            "dermatology",
            "dermatologist",
            "optometry",
            "optometrist",
            "optical",
            "eye care",
            "eye doctor",
            "lenscrafters",
            "vision center",
            "chiropractor",
            "chiropractic",
            "physical therapy",
            "physiotherapy",
            "podiatry",
            "radiology",
            "imaging center",
            "mri",
            "x-ray",
            "laboratory",
            "labcorp",
            "quest diagnostics",
            "pediatric",
            "pediatrics",
            "obgyn",
            "gynecology",
            "cardiology",
            "psychiatry",
            "psychiatrist",
            "psychology",
            "psychologist",
            "therapy",
            "therapist",
            "counseling",
            "mental health",
            "surgery",
            "surgical",
            "wellness",
            "healthcare",
            "medicine",
            "prescription",
            "copay",
            "co-pay",
            "vitamin",
            "vitamins",
            "supplement",
            "supplements",
            "gnc",
            "vitamin shoppe",
            "gym",
            "fitness",
            "planet fitness",
            "la fitness",
            "24 hour fitness",
            "equinox",
            "crossfit",
            "yoga",
            "pilates",
            "peloton",
            "gold's gym",
            "anytime fitness",
            "orangetheory",
            "spa",
            "massage",
            "acupuncture",
            "blue cross",
            "blue shield",
            "aetna",
            "cigna",
            "unitedhealthcare",
            "humana",
            "kaiser permanente",
            "medicaid",
            "medicare",
            "veterinary",
            "veterinarian",
            "vet clinic",
            "animal hospital",
        ),
    ),
    (
        "Entertainment",
        (
            "netflix",
            "spotify",
            "hulu",
            "disney+",
            "disneyplus",
            "disney plus",
            "hbo",
            "hbomax",
            "hbo max",
            "paramount+",
            "peacock",
            "apple tv",
            "apple music",
            "prime video",
            "youtube",
            "youtube premium",
            "pandora",
            "tidal",
            "deezer",
            "soundcloud",
            "audible",
            "cinema",
            "cinemas",
            "movie",
            "movies",
            "amc",
            "regal cinemas",
            "cinemark",
            "alamo drafthouse",
            "fandango",
            "theater",
            "theatre",
            "broadway",
            "concert",
            "live nation",
            "ticketmaster",
            "stubhub",
            "seatgeek",
            "museum",
            "gallery",
            "zoo",
            "aquarium",
            "amusement park",
            "theme park",
            "six flags",
            "cedar point",
            "disneyland",
            "disney world",
            "universal studios",
            "seaworld",
            "arcade",
            "bowling",
            "mini golf",
            "laser tag",
            "escape room",
            "casino",
            "dave & buster",
            "steam games",
            "epic games",
            "playstation",
            "xbox",
            "nintendo",
            "game pass",
            "twitch",
            "patreon",
            "gamestop",
            "game",
            "games",
            "board game",
            "comic",
            "comics",
            "hobby",
            "festival",
            "comedy club",
            "nightclub",
            "karaoke",
        ),
    ),
    (
        "Food and Drinks",
        (
            "restaurant",
            "restaurants",
            "diner",
            "eatery",
            "eateries",
            "bistro",
            "brasserie",
            "grill",
            "grille",
            "steakhouse",
            "buffet",
            "food court",
            "food truck",
            "cafe",
            "café",
            "cafeteria",
            "coffee",
            "coffeehouse",
            "coffee shop",
            "espresso",
            "tea house",
            "boba",
            "bubble tea",
            "juice bar",
            "smoothie",
            "bakery",
            "bakeries",
            "patisserie",
            "donut",
            "donuts",
            "doughnut",
            "bagel",
            "deli",
            "delicatessen",
            "sandwich",
            "sub shop",
            "pizzeria",
            "pizza",
            "sushi",
            "ramen",
            "noodle",
            "noodles",
            "dumpling",
            "pho",
            "taqueria",
            "taco",
            "tacos",
            "burrito",
            "cantina",
            "kebab",
            "gyro",
            "shawarma",
            "falafel",
            "poke bowl",
            "bbq",
            "barbecue",
            "seafood",
            "steak",
            "wings",
            "creamery",
            "ice cream",
            "gelato",
            "frozen yogurt",
            "froyo",
            "candy",
            "chocolate",
            "food",
            "foods",
            "eats",
            "kitchen",
            "bar & grill",
            "sports bar",
            "wine bar",
            "pub",
            "tavern",
            "taproom",
            "brewery",
            "brewpub",
            "brewing",
            "winery",
            "wine",
            "liquor",
            "spirits",
            "cocktail",
            "distillery",
            "mcdonald",
            "mcdonalds",
            "burger king",
            "wendy's",
            "wendys",
            "kfc",
            "taco bell",
            "chipotle",
            "popeyes",
            "chick-fil-a",
            "chick fil a",
            "panera",
            "dunkin",
            "tim hortons",
            "five guys",
            "shake shack",
            "in-n-out",
            "whataburger",
            "sonic drive",
            "arby's",
            "arbys",
            "domino's",
            "dominos",
            "papa john",
            "little caesar",
            "panda express",
            "olive garden",
            "applebee",
            "chili's",
            "cheesecake factory",
            "ihop",
            "denny's",
            "dennys",
            "waffle house",
            "cracker barrel",
            "starbucks",
            "peet's",
            "dutch bros",
            "caribou coffee",
            "qdoba",
            "jimmy john",
            "jersey mike",
            "grocery",
            "groceries",
            "supermarket",
            "grocery store",
            "farmers market",
            "bodega",
            "butcher",
            "kroger",
            "safeway",
            "trader joe",
            "whole foods",
            "aldi",
            "publix",
            "wegmans",
            "h-e-b",
            "ralphs",
            "vons",
            "albertsons",
            "stop & shop",
            "food lion",
            "harris teeter",
            "sprouts",
            "fresh market",
            "meijer",
            "winco",
            "food4less",
            "smart & final",
            "99 ranch",
            "hmart",
            "h mart",
            "instacart",
            "doordash",
            "grubhub",
            "uber eats",
            "ubereats",
            "seamless",
            "postmates",
            "caviar",
            "gopuff",
        ),
    ),
    (
        "Travel/Transportation",
        (
            "uber",
            "lyft",
            "taxi",
            "cab",
            "rideshare",
            "ride share",
            "gas station",
            "gasoline",
            "fuel",
            "shell",
            "chevron",
            "exxon",
            "mobil",
            "texaco",
            "citgo",
            "sunoco",
            "valero",
            "arco",
            "speedway",
            "wawa",
            "quiktrip",
            "sheetz",
            "transit",
            "public transit",
            "metro",
            "subway",
            "light rail",
            "commuter rail",
            "bus fare",
            "mta",
            "omny",
            "metrocard",
            "pay as you go",
            "e-zpass",
            "ezpass",
            "fastrak",
            "clipper card",
            "septa",
            "bart",
            "caltrain",
            "amtrak",
            "path train",
            "ferry",
            "tram",
            "trolley",
            "streetcar",
            "parking",
            "parking garage",
            "parking meter",
            "toll",
            "tolls",
            "tollway",
            "turnpike",
            "dmv",
            "car wash",
            "auto repair",
            "auto parts",
            "mechanic",
            "oil change",
            "jiffy lube",
            "valvoline",
            "autozone",
            "o'reilly auto",
            "napa auto",
            "pep boys",
            "discount tire",
            "firestone",
            "goodyear",
            "les schwab",
            "car rental",
            "rental car",
            "hertz",
            "avis",
            "enterprise rent",
            "national car",
            "alamo rent",
            "sixt",
            "zipcar",
            "turo",
            "scooter",
            "citibike",
            "bike share",
            "chargepoint",
            "electrify america",
            "supercharger",
            "hotel",
            "motel",
            "inn",
            "bed & breakfast",
            "hostel",
            "lodging",
            "resort",
            "airbnb",
            "vrbo",
            "marriott",
            "hilton",
            "hyatt",
            "holiday inn",
            "best western",
            "sheraton",
            "westin",
            "ritz-carlton",
            "four seasons",
            "days inn",
            "super 8",
            "la quinta",
            "comfort inn",
            "hampton inn",
            "doubletree",
            "wyndham",
            "motel 6",
            "airline",
            "airlines",
            "airways",
            "flight",
            "flights",
            "airfare",
            "delta air",
            "united airlines",
            "american airlines",
            "southwest airlines",
            "jetblue",
            "alaska airlines",
            "spirit airlines",
            "frontier airlines",
            "air canada",
            "lufthansa",
            "british airways",
            "emirates",
            "airport",
            "tsa precheck",
            "global entry",
            "expedia",
            "booking.com",
            "priceline",
            "kayak",
            "orbitz",
            "travelocity",
            "hotwire",
            "hopper",
            "trip.com",
            "agoda",
            "cruise",
            "carnival cruise",
            "royal caribbean",
            "norwegian cruise",
        ),
    ),
    (
        "Services",
        (
            "rent",
            "rent payment",
            "mortgage",
            "landlord",
            "property management",
            "hoa",
            "lease",
            "insurance",
            "geico",
            "progressive insurance",
            "allstate",
            "state farm",
            "liberty mutual",
            "nationwide",
            "farmers insurance",
            "usaa",
            "metlife",
            "electric bill",
            "electricity",
            "power bill",
            "pg&e",
            "con edison",
            "coned",
            "duke energy",
            "national grid",
            "water bill",
            "sewer",
            "gas bill",
            "natural gas",
            "utility",
            "utilities",
            "internet",
            "broadband",
            "comcast",
            "xfinity",
            "spectrum",
            "at&t",
            "verizon",
            "t-mobile",
            "tmobile",
            "sprint",
            "cox communications",
            "centurylink",
            "google fiber",
            "phone bill",
            "cell phone",
            "cellular",
            "cricket wireless",
            "metro pcs",
            "boost mobile",
            "mint mobile",
            "cable",
            "dish network",
            "directv",
            "subscription",
            "membership",
            "annual fee",
            "monthly fee",
            "bank fee",
            "atm fee",
            "service fee",
            "overdraft",
            "late fee",
            "finance charge",
            "interest charge",
            "accountant",
            "tax prep",
            "turbotax",
            "h&r block",
            "lawyer",
            "attorney",
            "law firm",
            "notary",
            "consulting",
            "financial advisor",
            "cleaning service",
            "house cleaning",
            "maid service",
            "laundry",
            "laundromat",
            "dry cleaning",
            "dry cleaner",
            "plumber",
            "plumbing",
            "electrician",
            "hvac",
            "lawn care",
            "landscaping",
            "pest control",
            "handyman",
            "contractor",
            "storage unit",
            "public storage",
            "extra space",
            "self storage",
            "post office",
            "usps",
            "ups store",
            "fedex",
            "dhl",
            "shipping",
            "postage",
            "salon",
            "hair salon",
            "barber",
            "barbershop",
            "nail salon",
            "daycare",
            "child care",
            "childcare",
            "tuition",
            "web hosting",
            "godaddy",
            "squarespace",
            "adobe",
            "microsoft 365",
            "office 365",
            "dropbox",
            "icloud",
            "google storage",
            "google one",
        ),
    ),
    (
        "Shopping",
        (
            "amazon",
            "amazon.com",
            "walmart",
            "target",
            "costco",
            "sam's club",
            "bj's wholesale",
            "best buy",
            "apple store",
            "microsoft store",
            "b&h photo",
            "newegg",
            "micro center",
            "ikea",
            "home depot",
            "lowe's",
            "lowes",
            "ace hardware",
            "harbor freight",
            "menards",
            "bed bath",
            "container store",
            "crate & barrel",
            "pottery barn",
            "west elm",
            "wayfair",
            "overstock",
            "world market",
            "homegoods",
            "tj maxx",
            "t.j. maxx",
            "tjmaxx",
            "marshalls",
            "ross dress",
            "nordstrom",
            "macy's",
            "macys",
            "bloomingdale",
            "kohl's",
            "kohls",
            "jcpenney",
            "dillard",
            "saks",
            "old navy",
            "banana republic",
            "h&m",
            "zara",
            "uniqlo",
            "forever 21",
            "urban outfitters",
            "anthropologie",
            "american eagle",
            "abercrombie",
            "hollister",
            "victoria's secret",
            "lululemon",
            "nike",
            "adidas",
            "under armour",
            "puma",
            "new balance",
            "vans",
            "converse",
            "foot locker",
            "finish line",
            "dsw",
            "shoe store",
            "shoes",
            "clothing",
            "apparel",
            "boutique",
            "department store",
            "mall",
            "outlet",
            "sephora",
            "ulta",
            "bath & body",
            "cosmetics",
            "makeup",
            "jewelry",
            "kay jewelers",
            "zales",
            "pandora jewelry",
            "tiffany",
            "sunglasses",
            "etsy",
            "ebay",
            "aliexpress",
            "shein",
            "temu",
            "mercari",
            "poshmark",
            "facebook marketplace",
            "amazon marketplace",
            "store",
            "shop",
            "retail",
            "gift shop",
            "toy store",
            "toys",
            "lego",
            "hobby lobby",
            "michaels",
            "joann",
            "party city",
            "office depot",
            "office max",
            "staples",
            "dollar store",
            "dollar tree",
            "dollar general",
            "family dollar",
            "five below",
            "petco",
            "petsmart",
            "chewy",
            "pet supplies",
            "furniture",
            "mattress",
            "electronics",
        ),
    ),
)


def _compile(keywords: tuple[str, ...]) -> re.Pattern[str]:
    # Match any keyword as a bounded token: not preceded/followed by a letter or digit.
    # So "gas" matches "shell gas" but not "las vegas"; "bar" matches "wine bar" not "barber".
    alt = "|".join(re.escape(k) for k in keywords)
    return re.compile(r"(?<![a-z0-9])(?:" + alt + r")(?![a-z0-9])")


_MATCHERS: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (cat, _compile(kws)) for cat, kws in _KEYWORDS
)


def from_plaid_pfc(primary: str | None) -> str:
    """Map a Plaid PFC primary to our taxonomy; unknown/absent → Other."""
    return PLAID_PFC_MAP.get((primary or "").strip().upper(), OTHER)


def from_text(name: str | None) -> str:
    """Classify from a merchant/item name via bounded keyword match; no hit → Other."""
    n = (name or "").lower()
    if not n.strip():
        return OTHER
    for category, matcher in _MATCHERS:
        if matcher.search(n):
            return category
    return OTHER


def categorize(*, name: str | None = None, plaid_pfc: str | None = None) -> str:
    """Best category for an item. Plaid's PFC is the strongest signal (already
    merchant-derived), so it's used when it resolves to something specific; otherwise fall
    back to the name classifier. Always returns a valid taxonomy member."""
    if plaid_pfc:
        pfc = from_plaid_pfc(plaid_pfc)
        if pfc != OTHER:
            return pfc
    result = from_text(name)
    return result if result in _VALID else OTHER
