"""Deterministic categorization into the fixed taxonomy (core/taxonomy.py).

The fast, free, offline first tier shared by every ingest source:
- **Bank (Plaid):** map Plaid's Personal Finance Category (already merchant-derived) to our
  taxonomy — the strongest signal, so it's tried first. Both levels are used: the *detailed*
  leaf outranks everything (it's the only signal that separates leaves whose primary straddles
  our taxonomy), and the coarse *primary* is trusted ahead of our keyword classifier only when
  Plaid reports decent confidence in it. See ``categorize()`` for the full precedence.
- **Manual / fallback:** a comprehensive keyword + merchant classifier over the item name.
- **Receipts:** the vision model picks from the taxonomy in the prompt; this service is the
  fallback if it declines, and it backfills historical bank rows in the migration.

For manual entries, if this returns ``Other`` the caller may escalate to the Gemini
fallback (services/extract.classify_category) — the "hybrid" path. This module itself stays
**pure and deterministic** (no I/O), so it's fully unit-testable and stable across the app.

Matching is **token-bounded** (a keyword matches only when not glued to other letters or
digits), so short keywords like ``gas`` match "shell gas" but not "las vegas", and ``bar``
would match "wine bar" but not "barber".
"""

from __future__ import annotations

import re

from app.core.taxonomy import REGULAR_CATEGORIES

OTHER = "Other"
_VALID = set(REGULAR_CATEGORIES)

# Plaid personal_finance_category PRIMARY → our category. Income/transfers/loan-payments are
# filtered out upstream as non-spending, so they aren't mapped here.
PLAID_PFC_MAP: dict[str, str] = {
    "FOOD_AND_DRINK": "Food and Drinks",
    "GENERAL_MERCHANDISE": "Shopping",
    "HOME_IMPROVEMENT": "Shopping",
    "PERSONAL_CARE": "Shopping",
    "ENTERTAINMENT": "Entertainment",
    "TRANSPORTATION": "Travel/Transportation",
    "TRAVEL": "Travel/Transportation",
    "MEDICAL": "Health",
    "GENERAL_SERVICES": "Services",
    "RENT_AND_UTILITIES": "Services",
    "BANK_FEES": "Services",
    "GOVERNMENT_AND_NON_PROFIT": "Other",
}

# Plaid personal_finance_category DETAILED → our category. The leaf is what Plaid actually
# inferred about the merchant, so it's a strictly better signal than the primary and is tried
# first. Crucially, several primaries straddle our taxonomy and the primary-only map gets them
# wrong for every leaf underneath:
#   - PERSONAL_CARE → Shopping, but gyms are Health and hair/laundry are Services.
#   - GENERAL_MERCHANDISE → Shopping, but a convenience store is Food and Drinks.
#   - GENERAL_SERVICES → Services, but _AUTOMOTIVE is Travel/Transportation.
#   - GOVERNMENT_AND_NON_PROFIT → Other, but a tax payment is a bill (Services).
# It also disambiguates the two "gas"es that the keyword classifier cannot: pumping fuel
# (TRANSPORTATION_GAS) vs the utility bill (RENT_AND_UTILITIES_GAS_AND_ELECTRICITY).
# Non-spending leaves (INCOME_*, TRANSFER_*, LOAN_PAYMENTS_*) are filtered upstream by the
# Plaid sync, so they're deliberately absent here — mirroring PLAID_PFC_MAP's coverage.
PLAID_PFC_DETAILED_MAP: dict[str, str] = {
    # --- Food and Drinks ---
    "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR": "Food and Drinks",
    "FOOD_AND_DRINK_COFFEE": "Food and Drinks",
    "FOOD_AND_DRINK_FAST_FOOD": "Food and Drinks",
    "FOOD_AND_DRINK_GROCERIES": "Food and Drinks",
    "FOOD_AND_DRINK_RESTAURANT": "Food and Drinks",
    "FOOD_AND_DRINK_VENDING_MACHINES": "Food and Drinks",
    "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK": "Food and Drinks",
    # A convenience store is a food run in practice, not general retail.
    "GENERAL_MERCHANDISE_CONVENIENCE_STORES": "Food and Drinks",
    # --- Shopping ---
    "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS": "Shopping",
    "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES": "Shopping",
    "GENERAL_MERCHANDISE_DEPARTMENT_STORES": "Shopping",
    "GENERAL_MERCHANDISE_DISCOUNT_STORES": "Shopping",
    "GENERAL_MERCHANDISE_ELECTRONICS": "Shopping",
    "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES": "Shopping",
    "GENERAL_MERCHANDISE_OFFICE_SUPPLIES": "Shopping",
    "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES": "Shopping",
    "GENERAL_MERCHANDISE_PET_SUPPLIES": "Shopping",
    "GENERAL_MERCHANDISE_SPORTING_GOODS": "Shopping",
    "GENERAL_MERCHANDISE_SUPERSTORES": "Shopping",
    "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE": "Shopping",
    "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE": "Shopping",
    "HOME_IMPROVEMENT_FURNITURE": "Shopping",
    "HOME_IMPROVEMENT_HARDWARE": "Shopping",
    "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT": "Shopping",
    # --- Entertainment ---
    "ENTERTAINMENT_CASINOS_AND_GAMBLING": "Entertainment",
    "ENTERTAINMENT_MUSIC_AND_AUDIO": "Entertainment",
    "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS": "Entertainment",
    "ENTERTAINMENT_TV_AND_MOVIES": "Entertainment",
    "ENTERTAINMENT_VIDEO_GAMES": "Entertainment",
    "ENTERTAINMENT_OTHER_ENTERTAINMENT": "Entertainment",
    # --- Travel/Transportation ---
    "TRANSPORTATION_BIKES_AND_SCOOTERS": "Travel/Transportation",
    "TRANSPORTATION_GAS": "Travel/Transportation",
    "TRANSPORTATION_PARKING": "Travel/Transportation",
    "TRANSPORTATION_PUBLIC_TRANSIT": "Travel/Transportation",
    "TRANSPORTATION_TAXIS_AND_RIDE_SHARES": "Travel/Transportation",
    "TRANSPORTATION_TOLLS": "Travel/Transportation",
    "TRANSPORTATION_OTHER_TRANSPORTATION": "Travel/Transportation",
    "TRAVEL_FLIGHTS": "Travel/Transportation",
    "TRAVEL_LODGING": "Travel/Transportation",
    "TRAVEL_RENTAL_CARS": "Travel/Transportation",
    "TRAVEL_OTHER_TRAVEL": "Travel/Transportation",
    # Car repair/service/parts is auto spending, not a professional service.
    "GENERAL_SERVICES_AUTOMOTIVE": "Travel/Transportation",
    # --- Health ---
    "MEDICAL_DENTAL_CARE": "Health",
    "MEDICAL_EYE_EXAMS_OPTOMETRIST": "Health",
    "MEDICAL_NURSING_CARE": "Health",
    "MEDICAL_PHARMACIES_AND_SUPPLEMENTS": "Health",
    "MEDICAL_PRIMARY_CARE": "Health",
    "MEDICAL_VETERINARY_SERVICES": "Health",
    "MEDICAL_OTHER_MEDICAL": "Health",
    # Our Health description explicitly covers "fitness, wellness".
    "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS": "Health",
    # --- Services ---
    "PERSONAL_CARE_HAIR_AND_BEAUTY": "Services",
    "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING": "Services",
    "PERSONAL_CARE_OTHER_PERSONAL_CARE": "Services",
    "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING": "Services",
    "GENERAL_SERVICES_CHILDCARE": "Services",
    "GENERAL_SERVICES_CONSULTING_AND_LEGAL": "Services",
    "GENERAL_SERVICES_EDUCATION": "Services",
    "GENERAL_SERVICES_INSURANCE": "Services",
    "GENERAL_SERVICES_POSTAGE_AND_SHIPPING": "Services",
    "GENERAL_SERVICES_STORAGE": "Services",
    "GENERAL_SERVICES_OTHER_GENERAL_SERVICES": "Services",
    "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE": "Services",
    "HOME_IMPROVEMENT_SECURITY": "Services",
    "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY": "Services",
    "RENT_AND_UTILITIES_INTERNET_AND_CABLE": "Services",
    "RENT_AND_UTILITIES_RENT": "Services",
    "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT": "Services",
    "RENT_AND_UTILITIES_TELEPHONE": "Services",
    "RENT_AND_UTILITIES_WATER": "Services",
    "RENT_AND_UTILITIES_OTHER_UTILITIES": "Services",
    "BANK_FEES_ATM_FEES": "Services",
    "BANK_FEES_FOREIGN_TRANSACTION_FEES": "Services",
    "BANK_FEES_INSUFFICIENT_FUNDS": "Services",
    "BANK_FEES_INTEREST_CHARGE": "Services",
    "BANK_FEES_LATE_PAYMENT": "Services",
    "BANK_FEES_OVERDRAFT_FEES": "Services",
    "BANK_FEES_OTHER_BANK_FEES": "Services",
    # A tax bill / agency fee behaves like a bill; a donation genuinely fits nowhere.
    "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES": "Services",
    "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT": "Services",
    # --- Other ---
    "GOVERNMENT_AND_NON_PROFIT_DONATIONS": "Other",
    "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT": "Other",
}

# Plaid's confidence in its own PFC guess. At LOW/UNKNOWN the guess is weak enough that our
# keyword classifier — which sees the merchant string Plaid may have failed to resolve — gets
# to answer first; the PFC is still used as a last resort before Other. Absent confidence is
# treated as trustworthy (older synced rows predate our capturing the field).
_WEAK_CONFIDENCE = frozenset({"LOW", "UNKNOWN"})


def pfc_is_confident(confidence: str | None) -> bool:
    """True when Plaid's PFC confidence is strong enough to outrank the keyword classifier."""
    return (confidence or "").strip().upper() not in _WEAK_CONFIDENCE


# Keyword / merchant substrings → category. First category with a hit wins, IN THIS ORDER,
# so specific buckets are checked before broad ones and known collisions resolve correctly:
#   - Food is before Travel/Transportation so "uber eats" (food) beats "uber" (rides).
#   - Shopping is LAST because "store"/"shop" are broad (a "coffee shop" is Food first).
# All lowercase; matched as bounded tokens (see _compile). Keep merchant names specific
# enough to avoid false hits; the confirm screen stays editable as the safety net.
_KEYWORDS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "Health",
        (
            "pharmacy",
            "pharmacies",
            "drugstore",
            "cvs",
            "walgreens",
            "rite aid",
            "duane reade",
            "doctor",
            "physician",
            "clinic",
            "medical",
            "med center",
            "hospital",
            "urgent care",
            "emergency room",
            "dental",
            "dentist",
            "orthodontist",
            "orthodontics",
            "dermatology",
            "dermatologist",
            "optometry",
            "optometrist",
            "optical",
            "eye care",
            "eye doctor",
            "lenscrafters",
            "vision center",
            "chiropractor",
            "chiropractic",
            "physical therapy",
            "physiotherapy",
            "podiatry",
            "radiology",
            "imaging center",
            "mri",
            "x-ray",
            "laboratory",
            "labcorp",
            "quest diagnostics",
            "pediatric",
            "pediatrics",
            "obgyn",
            "gynecology",
            "cardiology",
            "psychiatry",
            "psychiatrist",
            "psychology",
            "psychologist",
            "therapy",
            "therapist",
            "counseling",
            "mental health",
            "surgery",
            "surgical",
            "wellness",
            "healthcare",
            "medicine",
            "prescription",
            "copay",
            "co-pay",
            "vitamin",
            "vitamins",
            "supplement",
            "supplements",
            "gnc",
            "vitamin shoppe",
            "gym",
            "fitness",
            "planet fitness",
            "la fitness",
            "24 hour fitness",
            "equinox",
            "crossfit",
            "yoga",
            "pilates",
            "peloton",
            "gold's gym",
            "anytime fitness",
            "orangetheory",
            "spa",
            "massage",
            "acupuncture",
            "blue cross",
            "blue shield",
            "aetna",
            "cigna",
            "unitedhealthcare",
            "humana",
            "kaiser permanente",
            "medicaid",
            "medicare",
            "veterinary",
            "veterinarian",
            "vet clinic",
            "animal hospital",
        ),
    ),
    (
        "Entertainment",
        (
            "netflix",
            "spotify",
            "hulu",
            "disney+",
            "disneyplus",
            "disney plus",
            "hbo",
            "hbomax",
            "hbo max",
            "paramount+",
            "peacock",
            "apple tv",
            "apple music",
            "prime video",
            "youtube",
            "youtube premium",
            "pandora",
            "tidal",
            "deezer",
            "soundcloud",
            "audible",
            "cinema",
            "cinemas",
            "movie",
            "movies",
            "amc",
            "regal cinemas",
            "cinemark",
            "alamo drafthouse",
            "fandango",
            "theater",
            "theatre",
            "broadway",
            "concert",
            "live nation",
            "ticketmaster",
            "stubhub",
            "seatgeek",
            "museum",
            "gallery",
            "zoo",
            "aquarium",
            "amusement park",
            "theme park",
            "six flags",
            "cedar point",
            "disneyland",
            "disney world",
            "universal studios",
            "seaworld",
            "arcade",
            "bowling",
            "mini golf",
            "laser tag",
            "escape room",
            "casino",
            "dave & buster",
            "steam games",
            "epic games",
            "playstation",
            "xbox",
            "nintendo",
            "game pass",
            "twitch",
            "patreon",
            "gamestop",
            "game",
            "games",
            "board game",
            "comic",
            "comics",
            "hobby",
            "festival",
            "comedy club",
            "nightclub",
            "karaoke",
        ),
    ),
    (
        "Food and Drinks",
        (
            "restaurant",
            "restaurants",
            "diner",
            "eatery",
            "eateries",
            "bistro",
            "brasserie",
            "grill",
            "grille",
            "steakhouse",
            "buffet",
            "food court",
            "food truck",
            "cafe",
            "café",
            "cafeteria",
            "coffee",
            "coffeehouse",
            "coffee shop",
            "espresso",
            "tea house",
            "boba",
            "bubble tea",
            "juice bar",
            "smoothie",
            "bakery",
            "bakeries",
            "patisserie",
            "donut",
            "donuts",
            "doughnut",
            "bagel",
            "deli",
            "delicatessen",
            "sandwich",
            "sub shop",
            "pizzeria",
            "pizza",
            "sushi",
            "ramen",
            "noodle",
            "noodles",
            "dumpling",
            "pho",
            "taqueria",
            "taco",
            "tacos",
            "burrito",
            "cantina",
            "kebab",
            "gyro",
            "shawarma",
            "falafel",
            "poke bowl",
            "bbq",
            "barbecue",
            "seafood",
            "steak",
            "wings",
            "creamery",
            "ice cream",
            "gelato",
            "frozen yogurt",
            "froyo",
            "candy",
            "chocolate",
            "food",
            "foods",
            "eats",
            "kitchen",
            "bar & grill",
            "sports bar",
            "wine bar",
            "pub",
            "tavern",
            "taproom",
            "brewery",
            "brewpub",
            "brewing",
            "winery",
            "wine",
            "liquor",
            "spirits",
            "cocktail",
            "distillery",
            "mcdonald",
            "mcdonalds",
            "burger king",
            "wendy's",
            "wendys",
            "kfc",
            "taco bell",
            "chipotle",
            "popeyes",
            "chick-fil-a",
            "chick fil a",
            "panera",
            "dunkin",
            "tim hortons",
            "five guys",
            "shake shack",
            "in-n-out",
            "whataburger",
            "sonic drive",
            "arby's",
            "arbys",
            "domino's",
            "dominos",
            "papa john",
            "little caesar",
            "panda express",
            "olive garden",
            "applebee",
            "chili's",
            "cheesecake factory",
            "ihop",
            "denny's",
            "dennys",
            "waffle house",
            "cracker barrel",
            "starbucks",
            "peet's",
            "dutch bros",
            "caribou coffee",
            "qdoba",
            "jimmy john",
            "jersey mike",
            "grocery",
            "groceries",
            "supermarket",
            "grocery store",
            "farmers market",
            "bodega",
            "butcher",
            "kroger",
            "safeway",
            "trader joe",
            "whole foods",
            "aldi",
            "publix",
            "wegmans",
            "h-e-b",
            "ralphs",
            "vons",
            "albertsons",
            "stop & shop",
            "food lion",
            "harris teeter",
            "sprouts",
            "fresh market",
            "meijer",
            "winco",
            "food4less",
            "smart & final",
            "99 ranch",
            "hmart",
            "h mart",
            "instacart",
            "doordash",
            "grubhub",
            "uber eats",
            "ubereats",
            "seamless",
            "postmates",
            "caviar",
            "gopuff",
        ),
    ),
    (
        "Travel/Transportation",
        (
            "uber",
            "lyft",
            "taxi",
            "cab",
            "rideshare",
            "ride share",
            "gas station",
            "gasoline",
            "fuel",
            "shell",
            "chevron",
            "exxon",
            "mobil",
            "texaco",
            "citgo",
            "sunoco",
            "valero",
            "arco",
            "speedway",
            "wawa",
            "quiktrip",
            "sheetz",
            "transit",
            "public transit",
            "metro",
            "subway",
            "light rail",
            "commuter rail",
            "bus fare",
            "mta",
            "omny",
            "metrocard",
            "pay as you go",
            "e-zpass",
            "ezpass",
            "fastrak",
            "clipper card",
            "septa",
            "bart",
            "caltrain",
            "amtrak",
            "path train",
            "ferry",
            "tram",
            "trolley",
            "streetcar",
            "parking",
            "parking garage",
            "parking meter",
            "toll",
            "tolls",
            "tollway",
            "turnpike",
            "dmv",
            "car wash",
            "auto repair",
            "auto parts",
            "mechanic",
            "oil change",
            "jiffy lube",
            "valvoline",
            "autozone",
            "o'reilly auto",
            "napa auto",
            "pep boys",
            "discount tire",
            "firestone",
            "goodyear",
            "les schwab",
            "car rental",
            "rental car",
            "hertz",
            "avis",
            "enterprise rent",
            "national car",
            "alamo rent",
            "sixt",
            "zipcar",
            "turo",
            "scooter",
            "citibike",
            "bike share",
            "chargepoint",
            "electrify america",
            "supercharger",
            "hotel",
            "motel",
            "inn",
            "bed & breakfast",
            "hostel",
            "lodging",
            "resort",
            "airbnb",
            "vrbo",
            "marriott",
            "hilton",
            "hyatt",
            "holiday inn",
            "best western",
            "sheraton",
            "westin",
            "ritz-carlton",
            "four seasons",
            "days inn",
            "super 8",
            "la quinta",
            "comfort inn",
            "hampton inn",
            "doubletree",
            "wyndham",
            "motel 6",
            "airline",
            "airlines",
            "airways",
            "flight",
            "flights",
            "airfare",
            "delta air",
            "united airlines",
            "american airlines",
            "southwest airlines",
            "jetblue",
            "alaska airlines",
            "spirit airlines",
            "frontier airlines",
            "air canada",
            "lufthansa",
            "british airways",
            "emirates",
            "airport",
            "tsa precheck",
            "global entry",
            "expedia",
            "booking.com",
            "priceline",
            "kayak",
            "orbitz",
            "travelocity",
            "hotwire",
            "hopper",
            "trip.com",
            "agoda",
            "cruise",
            "carnival cruise",
            "royal caribbean",
            "norwegian cruise",
        ),
    ),
    (
        "Services",
        (
            "rent",
            "rent payment",
            "mortgage",
            "landlord",
            "property management",
            "hoa",
            "lease",
            "insurance",
            "geico",
            "progressive insurance",
            "allstate",
            "state farm",
            "liberty mutual",
            "nationwide",
            "farmers insurance",
            "usaa",
            "metlife",
            "electric bill",
            "electricity",
            "power bill",
            "pg&e",
            "con edison",
            "coned",
            "duke energy",
            "national grid",
            "water bill",
            "sewer",
            "gas bill",
            "natural gas",
            "utility",
            "utilities",
            "internet",
            "broadband",
            "comcast",
            "xfinity",
            "spectrum",
            "at&t",
            "verizon",
            "t-mobile",
            "tmobile",
            "sprint",
            "cox communications",
            "centurylink",
            "google fiber",
            "phone bill",
            "cell phone",
            "cellular",
            "cricket wireless",
            "metro pcs",
            "boost mobile",
            "mint mobile",
            "cable",
            "dish network",
            "directv",
            "subscription",
            "membership",
            "annual fee",
            "monthly fee",
            "bank fee",
            "atm fee",
            "service fee",
            "overdraft",
            "late fee",
            "finance charge",
            "interest charge",
            "accountant",
            "tax prep",
            "turbotax",
            "h&r block",
            "lawyer",
            "attorney",
            "law firm",
            "notary",
            "consulting",
            "financial advisor",
            "cleaning service",
            "house cleaning",
            "maid service",
            "laundry",
            "laundromat",
            "dry cleaning",
            "dry cleaner",
            "plumber",
            "plumbing",
            "electrician",
            "hvac",
            "lawn care",
            "landscaping",
            "pest control",
            "handyman",
            "contractor",
            "storage unit",
            "public storage",
            "extra space",
            "self storage",
            "post office",
            "usps",
            "ups store",
            "fedex",
            "dhl",
            "shipping",
            "postage",
            "salon",
            "hair salon",
            "barber",
            "barbershop",
            "nail salon",
            "daycare",
            "child care",
            "childcare",
            "tuition",
            "web hosting",
            "godaddy",
            "squarespace",
            "adobe",
            "microsoft 365",
            "office 365",
            "dropbox",
            "icloud",
            "google storage",
            "google one",
        ),
    ),
    (
        "Shopping",
        (
            "amazon",
            "amazon.com",
            "walmart",
            "target",
            "costco",
            "sam's club",
            "bj's wholesale",
            "best buy",
            "apple store",
            "microsoft store",
            "b&h photo",
            "newegg",
            "micro center",
            "ikea",
            "home depot",
            "lowe's",
            "lowes",
            "ace hardware",
            "harbor freight",
            "menards",
            "bed bath",
            "container store",
            "crate & barrel",
            "pottery barn",
            "west elm",
            "wayfair",
            "overstock",
            "world market",
            "homegoods",
            "tj maxx",
            "t.j. maxx",
            "tjmaxx",
            "marshalls",
            "ross dress",
            "nordstrom",
            "macy's",
            "macys",
            "bloomingdale",
            "kohl's",
            "kohls",
            "jcpenney",
            "dillard",
            "saks",
            "old navy",
            "banana republic",
            "h&m",
            "zara",
            "uniqlo",
            "forever 21",
            "urban outfitters",
            "anthropologie",
            "american eagle",
            "abercrombie",
            "hollister",
            "victoria's secret",
            "lululemon",
            "nike",
            "adidas",
            "under armour",
            "puma",
            "new balance",
            "vans",
            "converse",
            "foot locker",
            "finish line",
            "dsw",
            "shoe store",
            "shoes",
            "clothing",
            "apparel",
            "boutique",
            "department store",
            "mall",
            "outlet",
            "sephora",
            "ulta",
            "bath & body",
            "cosmetics",
            "makeup",
            "jewelry",
            "kay jewelers",
            "zales",
            "pandora jewelry",
            "tiffany",
            "sunglasses",
            "etsy",
            "ebay",
            "aliexpress",
            "shein",
            "temu",
            "mercari",
            "poshmark",
            "facebook marketplace",
            "amazon marketplace",
            "store",
            "shop",
            "retail",
            "gift shop",
            "toy store",
            "toys",
            "lego",
            "hobby lobby",
            "michaels",
            "joann",
            "party city",
            "office depot",
            "office max",
            "staples",
            "dollar store",
            "dollar tree",
            "dollar general",
            "family dollar",
            "five below",
            "petco",
            "petsmart",
            "chewy",
            "pet supplies",
            "furniture",
            "mattress",
            "electronics",
        ),
    ),
)


def _compile(keywords: tuple[str, ...]) -> re.Pattern[str]:
    # Match any keyword as a bounded token: not preceded/followed by a letter or digit.
    # So "gas" matches "shell gas" but not "las vegas"; "bar" matches "wine bar" not "barber".
    alt = "|".join(re.escape(k) for k in keywords)
    return re.compile(r"(?<![a-z0-9])(?:" + alt + r")(?![a-z0-9])")


_MATCHERS: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (cat, _compile(kws)) for cat, kws in _KEYWORDS
)


def from_plaid_pfc(primary: str | None) -> str:
    """Map a Plaid PFC primary to our taxonomy; unknown/absent → Other."""
    return PLAID_PFC_MAP.get((primary or "").strip().upper(), OTHER)


def from_plaid_pfc_detailed(detailed: str | None) -> str:
    """Map a Plaid PFC detailed leaf to our taxonomy; unknown/absent → Other.

    Falls back to the leaf's primary prefix when the leaf itself is unrecognized, so a value
    Plaid adds after this map was written still lands in the right broad bucket instead of
    Other. Plaid guarantees every leaf is prefixed with its primary.
    """
    key = (detailed or "").strip().upper()
    if not key:
        return OTHER
    mapped = PLAID_PFC_DETAILED_MAP.get(key)
    if mapped:
        return mapped
    # Unknown leaf: longest matching primary prefix wins (GENERAL_MERCHANDISE before GENERAL).
    for primary in sorted(PLAID_PFC_MAP, key=len, reverse=True):
        if key.startswith(primary):
            return PLAID_PFC_MAP[primary]
    return OTHER


def from_text(name: str | None) -> str:
    """Classify from a merchant/item name via bounded keyword match; no hit → Other."""
    n = (name or "").lower()
    if not n.strip():
        return OTHER
    for category, matcher in _MATCHERS:
        if matcher.search(n):
            return category
    return OTHER


def categorize(
    *,
    name: str | None = None,
    plaid_pfc: str | None = None,
    plaid_pfc_detailed: str | None = None,
    plaid_pfc_confidence: str | None = None,
) -> str:
    """Best category for an item, from every signal available, strongest first:

    1. **Detailed PFC** — Plaid's merchant-resolved leaf. Most specific signal we get, and the
       only one that separates leaves whose primary straddles our taxonomy (a gym vs a salon,
       fuel vs a utility bill), so it outranks everything.
    2. **Primary PFC**, when Plaid is confident in it — coarse but merchant-derived.
    3. **The keyword classifier** over the merchant/item name — our own signal, and better
       than a PFC that Plaid itself flagged LOW/UNKNOWN.
    4. **Primary PFC at weak confidence** — a guess beats no answer.

    Always returns a valid taxonomy member (``Other`` when nothing resolves).
    """
    if plaid_pfc_detailed:
        detailed = from_plaid_pfc_detailed(plaid_pfc_detailed)
        if detailed != OTHER:
            return detailed
    primary = from_plaid_pfc(plaid_pfc) if plaid_pfc else OTHER
    if primary != OTHER and pfc_is_confident(plaid_pfc_confidence):
        return primary
    result = from_text(name)
    if result in _VALID and result != OTHER:
        return result
    return primary if primary in _VALID else OTHER
